name: Documentation request
description: Request new documentation or an uplift to existing SRE-owned docs.
labels: ["new", "doc-request"]
body:
  - type: textarea
    id: dr
    attributes:
      label: Documentation request
      description: What docs would you like to see created or uplifted? Don't forget to include links! 
  - type: markdown
    attributes:
      value: "Thanks for raising a documentation request!"
