name: Task
description: Create a new piece of work
title: "Task: "
labels: ["new"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What work needs to be done?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: How do we measure or confirm that the work is done?
  - type: markdown
    attributes:
      value: |
        Make sure you add this to the **Fabric-SRE** project with **Status:** `Backlog`.
