name: New task
description: Create a new task (for Fabric SRE team)
labels: ["new"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What work needs to be done?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: How do we measure or confirm that the work is done?
  - type: markdown
    attributes:
      value: "Make sure you add this to the **Fabric-SRE** project with **Status:** `Backlog`."
  - type: checkboxes
    id: requirements
    attributes:
      label: Checks
      options:
        - label: Fabric-SRE project selected (if applicable)
          required: true
        - label: Milestone selected (if applicable)
          required: true
          
