name: Feature request
description: Request a new feature or enhancement to an SRE-owned product
labels: ["new", "feature-request"]
body:
  - type: markdown
    attributes:
      value: "Thanks for raising a feature request!"
  - type: textarea
    id: fr
    attributes:
      label: Feature Request
      description: What feature or enhancement would you like to see?
  - type: textarea
    id: fr-value
    attributes:
      label: Value added
      description: What value will this feature add?
