name: Fabric SRE - Investigation
description: Create issue to execute a short-term structured exploration of a specific issue, an unanswered question, or assessment of potential solutions.
title: "[Investigation]: "
labels: ["investigation"]
projects: ["anzx/217"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Investigation Description
      placeholder: Investigation description
  - type: checkboxes
    id: checks
    attributes:
      label: Closure checks
      options:
        - label: Investigation published in Confluence. [Fabric SRE - Investigations](https://confluence.service.anz/x/SVH8VQ)
        - label: Investigation has been reviewed.
